### ISSUE TITLE
Numbers stopped working today. Using telnyx, when I try to save API settings I get this error 

### ISSUE THREAD

**Issue by getsean** [0perationPrivacy/VoIP#187] opened 2023-03-01 21:24 UTC
![image](https://user-images.githubusercontent.com/77656279/222268107-91bc98c3-38de-4003-90c7-c4f963ab6fa9.png)

**Comment by 0perationPrivacy** [comment] 2023-03-01 22:48
seems like a telnyx issue for now. looking into it.

**Comment by 0perationPrivacy** [comment] 2023-03-01 22:51
I can send receive fine on Twilio numbers.
On telnyx, i can send but not receive. Definitely a telco issue.

**Comment by ail1020** [comment] 2023-03-13 05:02
I too am not able to receive sms with Telnyx. I tried changing the webhook info in Telnyx to point at webhook.site and that seems to be working fine. However when it is pointed at https://voip.operationprivacy.com/api/setting/receive-sms/telnyx I do not get any of my messages.

**Comment by ail1020** [comment] 2023-03-13 17:40
@getsean me too. It took me longer to notice as I don't get many messages, but my last received sms was Feb 27th. I don't see the error you got, I've tried re-saving my api key and requesting phone number and it works fine for that. I just don't receive any messages. I haven't gone as far as deleting the profile and re-adding it, but maybe that's where you ran into the issue. Been watching this issue for about a week now hoping it'd get traction and finally decided to login and comment to see if that helped. Might have to try transferring to twilio if this continues much longer though.

**Comment by tomkel** [comment] 2023-03-13 20:59
Perhaps it's a regression from this recent commit? #186

**Comment by ail1020** [comment] 2023-03-13 22:10
That was my first thought, but that file seems to have had a massive formatting update so almost everything changed and I didn't have the time to try looking for the actual changes.

**Comment by clarkmerrick** [comment] 2023-03-14 06:55
I rolled back to cff57e9 and it worked

**Comment by 0perationPrivacy** [comment] 2023-03-14 07:06
> I rolled back to [cff57e9](https://github.com/0perationPrivacy/VoIP/commit/cff57e92bd25abff5a1fbd9706bd2e986aee94fd) and it worked

Thank you for your troubleshooting, looking into it for a fix as soon as I get a chance.

**Comment by huzaifa3115** [comment] 2023-03-14 17:45
Issue has been fixed (https://github.com/0perationPrivacy/VoIP/pull/190)

**Closed by huzaifa3115** 2023-03-14 17:45 UTC
Labels: bug
